-- MySQL Script generated by MySQL Workbench
-- 04/04/16 21:38:56
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema db_tcc
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_tcc
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_tcc` DEFAULT CHARACTER SET utf8 ;
USE `db_tcc` ;

-- -----------------------------------------------------
-- Table `db_tcc`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_tcc`.`usuarios` (
  `usuario_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `login` VARCHAR(15) NOT NULL,
  `senha` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`usuario_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_tcc`.`paginas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_tcc`.`paginas` (
  `paginas_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`paginas_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_tcc`.`usuarios_paginas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_tcc`.`usuarios_paginas` (
  `usuario_id` INT UNSIGNED NOT NULL,
  `paginas_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`usuario_id`, `paginas_id`),
  INDEX `ind_usuarios_paginas_pagina` (`paginas_id` ASC),
  INDEX `ind_usuarios_paginas_usuario` (`usuario_id` ASC),
  CONSTRAINT `fk_usuarios_paginas_usuarios`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `db_tcc`.`usuarios` (`usuario_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuarios_paginas_pagina`
    FOREIGN KEY (`paginas_id`)
    REFERENCES `db_tcc`.`paginas` (`paginas_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
